# docker-compose.yml
version: '3'

services:
  vault:
    image: vaultwarden/server:1.27.0
    container_name: vault
    restart: always
    volumes:
      - /opt/vault/data:/data
    environment:
      WEBSOCKET_ENABLED: 'true' # Required to use websockets
      SIGNUPS_ALLOWED: 'false'   # set to false to disable signups
    labels:
      - "traefik.http.routers.vault.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.vault.entrypoints=websecure"
      - "traefik.http.routers.vault.tls.certresolver=letsencrypt"
      - "traefik.http.services.vault.loadbalancer.server.port=80"
      - "traefik.docker.network=web"

networks:
  default:
    external:
      name: web
